name: Publish Extension to NuGet.org

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Add package sources
      run: |
        dotnet nuget add source https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json -n CommunityToolkit-Labs
        
    - name: Restore dependencies
      run: dotnet restore src/WindowSill.ShortTermReminder/WindowSill.ShortTermReminder.csproj
      
    - name: Build project
      run: dotnet build src/WindowSill.ShortTermReminder/WindowSill.ShortTermReminder.csproj --configuration Release --no-restore
      
    - name: Create NuGet package
      run: dotnet pack src/WindowSill.ShortTermReminder/WindowSill.ShortTermReminder.csproj --configuration Release --no-build --output ./artifacts
      
    - name: Publish to NuGet.org
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts/*.nupkg